---

# Address or path of
address: tcp://ram.rtr.0l.de:4141
# address: serial:/dev/ttyS0

# Credentials for authenticating against PDU
username: admin
password: admin

# Caching PDU status
ttl: 1m

# TLS settings for REST API
tls:
  cacert: certs/ca.crt 
  cert: certs/server.crt
  key: certs/server.key
  insecure: false

# Access control list
acl:
  
- # Matches the commonName of the client certificate (mTLS)
  # This is a regular expression
  name: client1

  # Allow getting status
  status: true

  # Allow clearing maximum current
  clear: true

  # Per outlet access
  outlets:
  - # Match the outlet ID
    # This is a regular expression
    id: "*"

    # List of access permissions
    access:
    - switch # Includes reboot
    - lock

