---

# Address or path of
address: tcp://ram.rtr.0l.de:4141
# address: serial:/dev/ttyS0

# Credentials for authenticating against PDU
username: admin
password: admin

# Caching PDU status
ttl: 1m

# TLS settings for REST API
tls:
  cacert: certs/ca.crt 
  cert: certs/client1.crt
  key: certs/client1.key
  insecure: false

# Access control list
acl:
  
- # Matches the commonName of the client certificate (mTLS)
  # This is a regular expression
  name: client1

  operations:
  - status
  - status-outlet-all
  - temperature
  - who-am-i
  - clear-maximum-currents
  - status-outlet
  - switch-outlet
  - lock-outlet
  - reboot-outlet

  # Per outlet operations
  outlets:
  - # Match the outlet ID
    # This is a regular expression
    id: ".*"

    # List of *-outlet operations
    operations:
    - switch # Includes reboot
    - lock

- name: client2

  operations:
  - temperature
  - who-am-i
