---
# SPDX-FileCopyrightText: 2024 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# Address or path of PDU
address: tcp://ram.rtr.0l.de:4142
# address: http://localhost:8080
# address: serial:/dev/ttyS0

# Time between consecutive status updates
poll_interval: 10s

# Listen address:port for built-in HTTP(s) server
listen: :8080

# Enable Prometheus exporter
metrics: true

# Output format for pductl
# format: json
# format: csv
# format: markdown
# format: html
# format: tsv
format: pretty
# format: pretty-bold
# format: pretty-rounded
# format: pretty-light
# format: pretty-double
# format: pretty-colored-bright
# format: pretty-colored-dark

# Credentials for authenticating against PDU
username: admin
password: admin

# TLS settings for REST API
# tls:
#   cacert: certs/ca.crt 
#   cert: certs/server.crt
#   key: certs/server.key
#   insecure: false

# Access control list
acl:
  
- # Matches the commonName of the client certificate (mTLS)
  # This is a regular expression
  name: client1

  operations:
  - status
  - status-outlet-all
  - temperature
  - who-am-i
  - clear-maximum-currents
  - status-outlet
  - switch-outlet
  - lock-outlet
  - reboot-outlet

  # Per outlet operations
  outlets:
  - # Match the outlet ID
    # This is a regular expression
    id: ".*"

    # List of *-outlet operations
    operations:
    - switch # Includes reboot
    - lock

- name: client2

  operations:
  - temperature
  - who-am-i
