# SPDX-FileCopyrightText: 2024 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "pductl"
SPDX-PackageSupplier = "Steffen Vogel <post@steffenvogel.de>"
SPDX-PackageDownloadLocation = "https://github.com/stv0g/pductl"

[[annotations]]
path = ["go.sum", "*.gen.go", "flake.lock", "docs/**.md", "**/*.gen.go"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Steffen Vogel <post@steffenvogel.de>"
SPDX-License-Identifier = "Apache-2.0"
